#!/bin/bash
# Test script for invitation flow

echo "=========================================="
echo "  INVITATION FLOW TEST"
echo "=========================================="
echo ""
echo "Prerequisites:"
echo "1. Server phải đang chạy (port 5501)"
echo "2. Database đã có test users (Alice, Bob, etc.)"
echo ""
echo "Test Scenarios:"
echo "=========================================="
echo ""
echo "SCENARIO 1: Normal Invite Flow"
echo "  Terminal 1: Login as Alice (pass: 123)"
echo "  Terminal 2: Login as Bob (pass: 123)"
echo "  Alice clicks on Bob in player list"
echo "  → Alice sees: 'Invitation sent to Bob. Waiting for response...'"
echo "  → Bob sees: 'Alice has sent you an invitation to play'"
echo "  Bob clicks ACCEPT"
echo "  → Both go to PLACING_SHIPS screen"
echo ""
echo "SCENARIO 2: Decline Invite"
echo "  Alice invites Bob"
echo "  Bob clicks DECLINE"
echo "  → Bob returns to lobby"
echo "  → Alice sees: 'Bob declined the invitation!'"
echo "  Alice clicks X button"
echo "  → Alice returns to lobby"
echo ""
echo "SCENARIO 3: Cancel Invite"
echo "  Alice invites Bob"
echo "  → Alice sees waiting dialog with CANCEL button"
echo "  Alice clicks CANCEL"
echo "  → Alice returns to lobby"
echo "  → Bob sees: 'Invitation was cancelled!'"
echo ""
echo "=========================================="
echo "Press Enter to start client..."
read

cd "$(dirname "$0")"
./run_client.sh
